### ISSUE TITLE
Automatic publishing broken due to Specberus errors

### ISSUE THREAD

**Issue by reillyeon** [w3c/deviceorientation#100]
@xfq, can you take a look at these errors?

```
Specberus Errors:
  Wrong syntax for Latest Version link.
    {
      name: 'headers.dl',
      section: 'front-matter',
      rule: 'docIDLatestVersion'
    }
  Missing `data-editor-id` attribute for editor(s): Devices and Sensors Working Group
       .
    { name: 'headers.dl', section: 'front-matter', rule: 'editorSection' }

Details: https://labs.w3.org/echidna/api/status?id=6f885bbf-3aaa-4d8c-b23b-88414e12c7de
```

**Comment by xfq** [comment]
The first error is because the Latest Version link is an http URL. I have fixed it.

The second error is because the Pubrules checker [needs one or more editor ids in the markup](https://github.com/w3c/echidna/wiki/Preparing-your-document#data-editor-id), which is the id associated with the W3C account of the individual, but we did not specify who is the editor(s) of this document (the editor is "Devices and Sensors Working Group").

**Comment by reillyeon** [comment]
Is there something we can do to resolve this other than listing specific editors?

**Comment by xfq** [comment]
I don't think there is anything we can do without modifying our existing system. @deniak any ideas?

**Comment by deniak** [comment]
Indeed, the current system expects a list of users (identified by their id) as the editors of the specification. While it's tricky to change the whole data model, we could add an exception for WG and remove the need for the `data-editor-id` in such case. I'll try to find time to implement this.

**Comment by deniak** [comment]
@xfq @reillyeon can you give it another try? I added the exception so the error should no longer block the publication of this document.

**Comment by reillyeon** [comment]
Looks like it passed: https://github.com/w3c/deviceorientation/runs/6828523128
