### ISSUE TITLE
Is the editor's draft still maintained?

### ISSUE THREAD

**Issue by miguelao** [w3c/deviceorientation#36]
I'm a bit confused, the [Editor's Draft](https://w3c.github.io/deviceorientation/spec-source-orientation.html) is dated `26 February 2016` and the [Candidate Recommendation](https://www.w3.org/TR/orientation-event/) is dated `18 August 2016`, but there seems to be [commits in between](https://github.com/w3c/deviceorientation/commits/gh-pages), does this mean that the Editor's Draft is unmaintained ?

**Comment by timvolodine** [comment]
yes it is, sorry for the confusion, updated the date
https://github.com/w3c/deviceorientation/pull/37

**Comment by miguelao** [comment]
Thanks!

**Comment by ashimura** [comment]
Thanks for your comment, @miguelao ! And thanks for your update @timvolodine !

I just wanted to remind you that the spec draft for DeviceOrientation is already a Candidate Recommendation (CR) and we don't actually update the spec draft for publication after CR.

Unfortunately, we need to publish another CR due to lack of implementations for compassneedscalibration ( #38 ), though.
