### ISSUE TITLE
Add integration with Permissions Policy

### ISSUE THREAD

**Issue by reillyeon** [w3c/deviceorientation#64]
This has already been implemented in Chrome ([issue 796894](https://bugs.chromium.org/p/chromium/issues/detail?id=796894)) based on the [Feature Policy specification](https://github.com/w3c/webappsec-feature-policy/blob/master/features.md#sensor-features) however this should be mentioned directly in this specification.

**Comment by anssiko** [comment]
Given both Safari and Firefox seem to restricted these events to top-level document and same-origin frames they'd comply with the default Feature Policy behavior of default allowlist set to ["self"]. Correct?

If that's the case, this seems like an obvious addition to the spec. I suspect it was not added to the spec in tandem with the Chrome implementation work due to the unfortunate fact this spec was unmaintained at that time.

**Comment by reillyeon** [comment]
Discussed at TPAC 2019 F2F. Resolved to implement this issue.

https://www.w3.org/2019/09/19-dap-minutes.html#x16

**Comment by xfq** [comment]
Note that Feature Policy has been renamed: https://github.com/w3c/webappsec-permissions-policy/pull/379

**Comment by rakuco** [comment]
For the record: both Blink and WebKit already integrate this API with the Permissions Policy spec, but Gecko does not.

When it comes to permissions policy tokens:
* Blink and WebKit use the same ones for ondevicemotion, "accelerometer" and "gyroscope"
* Blink uses "accelerometer" and "gyroscope" for ondeviceorientation and "accelerometer", "gyroscope" and "magnetometer" for ondeviceorientationabsolute.
* WebKit does not implement ondeviceorientationabsolute but requires "accelerometer", "gyroscope" and "magnetometer" for ondeviceorientation. Curiously, it still supports the `initDeviceOrientationEvent()` call that takes an `absolute` parameter which was removed from the spec in 2012 (possibly because the IDL file wasn't updated after Blink came to existence).

**Comment by rakuco** [comment]
> My proposal is to standardize Blink's behavior (i.e. require "accelerometer"+"gyroscope" for ondevicemotion and ondeviceorientation, and "accelerometer"+"gyroscope"+"magnetometer" for ondeviceorientationabsolute) instead.

The current text in the spec does give some leeway to implementations to use a magnetometer for ondeviceorientation:

> The [deviceorientation](https://w3c.github.io/deviceorientation/#def-deviceorientation) event tries to provide relative values for the three angles (relative to some arbitrary orientation), based on just the accelerometer and the gyroscope. The implementation can still decide to provide [absolute](https://w3c.github.io/deviceorientation/#dom-deviceorientationevent-absolute) orientation if relative is not available or the resulting data is more accurate. In either case, the absolute property must be set accordingly to reflect the choice.

The Gecko implementation seems to do this on e.g. Android: https://searchfox.org/mozilla-central/rev/8acfbe4ba09b46b91c862dc2fbc064d4fc1bac9a/dom/events/EventListenerManager.cpp#710

In order for the spec to be airtight, we'd need to either require "magnetometer" or stop allowing implementations to fall back to absolute orientation.

**Comment by reillyeon** [comment]
Could the we specify that implementations may only fall back to absolute orientation if the document has "magnetometer" permission?

**Comment by rakuco** [comment]
I think that could work, even though it doesn't match the behavior of any of the implementations :smile: 

I'll work on a draft patch.

**Comment by reillyeon** [comment]
I believe that is how Chromium works: https://source.chromium.org/chromium/chromium/src/+/main:content/browser/generic_sensor/frame_sensor_provider_proxy.cc;l=24;drc=73975654a11ff311bdd908f2a699096ba5dd07e2

**Comment by rakuco** [comment]
Ah, good point, I was only looking at the [Blink-side checks](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/device_orientation/device_orientation_controller.cc;l=86;drc=047c7dc4ee1ce908d7fea38ca063fa2f80f92c77) but forgot that there are content-side checks as well.
